version: 1
disable_existing_loggers: false
formatters:
  json:
    format: '{"level": "%(levelname)s", "message": "%(message)s", "timestamp": "%(asctime)s", "file": "%(pathname)s", "line": "%(lineno)d"}'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
handlers:
  stdout:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
loggers:
  root:
    level: INFO
    handlers:
    - stdout
