[tool.ruff]

line-length = 100

select = ["E", "F", "W", "I"]

extend-exclude = [
    "*.md",
    "*.json",
    "*.yml",
    "*.yaml",
    "*.lock",
    "*.log"
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.isort]
force-single-line = true
